const mongoose = require('mongoose');
const Job = require('./models/job.model');

mongoose.connect('mongodb://localhost:27017/tracking-app', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
}).then(async () => {
    console.log('MongoDB connected for seeding');

    const jobs = [
        {
            id: 'JOB-2025-001',
            status: 'in-transit',
            progress: 60,
            distanceRemaining: 80,
            pickupLocation: 'Thamel, Kathmandu',
            deliveryLocation: 'Lakeside, Pokhara',
            currentLocation: 'Mugling, Bagmati',
            pickupTime: '9:00 AM',
            eta: '3:00 PM',
            lastUpdate: new Date(),
            pickupCoords: [27.7172, 85.3240],
            deliveryCoords: [28.2096, 83.9856],
            currentCoords: [27.6833, 84.4167],
            driverInfo: {
                name: 'Ramesh Shrestha',
                phone: '+977 984-123-4567',
                rating: 4.7,
                vehicle: 'Truck - NP-1234',
                isOnline: true,
            },
            customerInfo: {
                name: 'Himalayan Traders',
                company: 'Himalayan Traders Pvt Ltd',
                phone: '+977 985-987-6543',
                email: 'contact@himalayantraders.com',
            },
            liveUpdates: [
                { id: 1, timestamp: new Date(Date.now() - 5 * 60000), icon: 'fas fa-truck', message: 'Vehicle passed through Mugling' },
                { id: 2, timestamp: new Date(Date.now() - 15 * 60000), icon: 'fas fa-gas-pump', message: 'Driver stopped for fuel at Narayanghat' },
                { id: 3, timestamp: new Date(Date.now() - 30 * 60000), icon: 'fas fa-route', message: 'Route updated due to road conditions' },
                { id: 4, timestamp: new Date(Date.now() - 45 * 60000), icon: 'fas fa-check', message: 'Package picked up in Kathmandu' },
            ],
            customer: {
                name: 'Himalayan Traders',
                email: 'contact@himalayantraders.com',
                phone: '+977 985-987-6543',
                company: 'Himalayan Traders Pvt Ltd',
            },
            pickup: {
                address: '123 Thamel Street',
                city: 'Kathmandu',
                state: 'Bagmati',
                zipCode: '44600',
                contactPerson: 'Suresh Lama',
                contactPhone: '+977 985-111-2222',
                instructions: 'Pickup from warehouse entrance',
            },
            delivery: {
                address: '456 Lakeside Road',
                city: 'Pokhara',
                state: 'Gandaki',
                zipCode: '33700',
                contactPerson: 'Anita Sharma',
                contactPhone: '+977 985-333-4444',
                instructions: 'Deliver to reception',
            },
            jobDetails: {
                type: 'Freight',
                priority: 'medium',
                scheduledDate: new Date(),
                scheduledTime: '9:00 AM',
                estimatedDuration: 360, // minutes
                specialInstructions: 'Handle with care',
                requiresSignature: true,
                fragileItems: false,
                heavyItems: true,
            },
            assignedTo: new mongoose.Types.ObjectId(), // Replace with actual User ID
            notes: 'Ensure timely delivery due to client urgency',
            etaStatus: 'on-time',
            isUrgent: false,
        },
        {
            id: 'JOB-2025-002',
            status: 'in-transit',
            progress: 45,
            distanceRemaining: 150,
            pickupLocation: 'Main Road, Biratnagar',
            deliveryLocation: 'Sauraha, Chitwan',
            currentLocation: 'Itahari',
            pickupTime: '7:30 AM',
            eta: '4:30 PM',
            lastUpdate: new Date(),
            pickupCoords: [26.4542, 87.2797],
            deliveryCoords: [27.5824, 84.4936],
            currentCoords: [26.6646, 87.2718],
            driverInfo: {
                name: 'Sita Gurung',
                phone: '+977 981-234-5678',
                rating: 4.8,
                vehicle: 'Van - NP-5678',
                isOnline: true,
            },
            customerInfo: {
                name: 'Nepal Logistics',
                company: 'Nepal Logistics Ltd',
                phone: '+977 986-876-5432',
                email: 'info@nepalogistics.com',
            },
            liveUpdates: [
                { id: 1, timestamp: new Date(Date.now() - 10 * 60000), icon: 'fas fa-truck', message: 'Vehicle passed through Itahari' },
                { id: 2, timestamp: new Date(Date.now() - 25 * 60000), icon: 'fas fa-exclamation-triangle', message: 'Traffic delay reported near Dharan' },
                { id: 3, timestamp: new Date(Date.now() - 40 * 60000), icon: 'fas fa-check', message: 'Package picked up in Biratnagar' },
            ],
            customer: {
                name: 'Nepal Logistics',
                email: 'info@nepalogistics.com',
                phone: '+977 986-876-5432',
                company: 'Nepal Logistics Ltd',
            },
            pickup: {
                address: '789 Main Road',
                city: 'Biratnagar',
                state: 'Koshi',
                zipCode: '56613',
                contactPerson: 'Rajesh Yadav',
                contactPhone: '+977 984-555-6666',
                instructions: 'Pickup from store front',
            },
            delivery: {
                address: '101 Sauraha Street',
                city: 'Chitwan',
                state: 'Bagmati',
                zipCode: '44200',
                contactPerson: 'Pooja Thapa',
                contactPhone: '+977 985-777-8888',
                instructions: 'Deliver to warehouse',
            },
            jobDetails: {
                type: 'Parcel',
                priority: 'high',
                scheduledDate: new Date(),
                scheduledTime: '7:30 AM',
                estimatedDuration: 540,
                specialInstructions: 'Urgent delivery required',
                requiresSignature: false,
                fragileItems: true,
                heavyItems: false,
            },
            assignedTo: new mongoose.Types.ObjectId(),
            notes: 'Avoid peak traffic hours',
            etaStatus: 'delayed',
            isUrgent: true,
        },
        {
            id: 'JOB-2025-003',
            status: 'delayed',
            progress: 30,
            distanceRemaining: 200,
            pickupLocation: 'Patan, Lalitpur',
            deliveryLocation: 'Siddharthanagar, Bhairahawa',
            currentLocation: 'Hetauda',
            pickupTime: '8:00 AM',
            eta: '6:00 PM',
            lastUpdate: new Date(),
            pickupCoords: [27.6766, 85.3147],
            deliveryCoords: [27.5067, 83.4526],
            currentCoords: [27.4289, 85.0322],
            driverInfo: {
                name: 'Hari Thapa',
                phone: '+977 982-345-6789',
                rating: 4.5,
                vehicle: 'Truck - NP-9012',
                isOnline: true,
            },
            customerInfo: {
                name: 'Everest Enterprises',
                company: 'Everest Enterprises',
                phone: '+977 984-765-4321',
                email: 'contact@everestent.com',
            },
            liveUpdates: [
                { id: 1, timestamp: new Date(Date.now() - 10 * 60000), icon: 'fas fa-truck', message: 'Vehicle delayed in Hetauda due to roadblock' },
                { id: 2, timestamp: new Date(Date.now() - 20 * 60000), icon: 'fas fa-exclamation-triangle', message: 'Delay reported due to construction' },
                { id: 3, timestamp: new Date(Date.now() - 35 * 60000), icon: 'fas fa-check', message: 'Package picked up in Lalitpur' },
            ],
            customer: {
                name: 'Everest Enterprises',
                email: 'contact@everestent.com',
                phone: '+977 984-765-4321',
                company: 'Everest Enterprises',
            },
            pickup: {
                address: '321 Patan Road',
                city: 'Lalitpur',
                state: 'Bagmati',
                zipCode: '44700',
                contactPerson: 'Manoj Shrestha',
                contactPhone: '+977 984-999-0000',
                instructions: 'Pickup from office',
            },
            delivery: {
                address: '654 Siddharthanagar',
                city: 'Bhairahawa',
                state: 'Lumbini',
                zipCode: '32900',
                contactPerson: 'Rita Gurung',
                contactPhone: '+977 985-111-2222',
                instructions: 'Deliver to store',
            },
            jobDetails: {
                type: 'Freight',
                priority: 'low',
                scheduledDate: new Date(),
                scheduledTime: '8:00 AM',
                estimatedDuration: 600,
                specialInstructions: 'Check for roadblocks',
                requiresSignature: true,
                fragileItems: false,
                heavyItems: true,
            },
            assignedTo: new mongoose.Types.ObjectId(),
            notes: 'Monitor for delays',
            etaStatus: 'delayed',
            isUrgent: false,
        },
    ];

    await Job.deleteMany({});
    await Job.insertMany(jobs);
    console.log('Jobs seeded successfully');
    mongoose.connection.close();
}).catch(err => {
    console.error('Seeding error:', err);
    mongoose.connection.close();
});